In [2]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().resolve().name == 'notebooks' else Path.cwd().resolve()

In [3]:
RAW_PATH_1 = PROJECT_ROOT / 'data/raw/hospital_1.csv'
RAW_PATH_2 = PROJECT_ROOT / 'data/raw/hospital_2.csv'
RAW_PATH_3 = PROJECT_ROOT / 'data/raw/hospital_3.csv'

df_1 = pd.read_csv(RAW_PATH_1)
df_2 = pd.read_csv(RAW_PATH_2)
df_3 = pd.read_csv(RAW_PATH_3)

display(df_1.head())
display(df_2.head())
display(df_3.head())

,Patient_ID,Age,Gender,Hospital,Hospital_Type,Diagnosis,Treatment_Cost,Doctor_Experience_Years,Doctor_Availability,Cleanliness_Score,Economic_Status,Outcome,Insurance,Region,Hospital_ID
0,P10000,69.0,MALE,MediLife,Government,Asthma,18661.47,4.0,5,3,Middle,Recovered,No,West,H1
1,P10001,32.0,MALE,MediLife,Government,Covid,28716.33,37.0,5,2,Middle,Under Treatment,Yes,West,H1
2,P10002,NaN,female,MediLife,Government,Covid,40662.23,28.0,7,4,Low,Under Treatment,NaN,north,H1
3,P10003,38.0,Female,MediLife,Government,Covid,33828.66,37.0,3,3,Middle,Recovered,No,north,H1
4,P10004,41.0,female,MediLife,Government,Asthma,12622.96,24.0,11,5,Low,Recovered,NaN,South,H1

,Patient_ID,Age,Gender,Hospital,Hospital_Type,Diagnosis,Treatment_Cost,Doctor_Experience_Years,Doctor_Availability,Cleanliness_Score,Economic_Status,Outcome,Insurance,Region,Hospital_ID
0,P10000,69.0,MALE,Sunrise,Private,Asthma,24259.911,4.0,5,3,Middle,Recovered,No,West,H2
1,P10001,32.0,MALE,Sunrise,Private,Covid,37331.229,37.0,5,2,Middle,Under Treatment,Yes,West,H2
2,P10002,NaN,female,Sunrise,Private,Covid,52860.899,28.0,7,4,Low,Under Treatment,NaN,north,H2
3,P10003,38.0,Female,Sunrise,Private,Covid,43977.258,37.0,3,3,Middle,Recovered,No,north,H2
4,P10004,41.0,female,Sunrise,Private,Asthma,16409.848,24.0,11,5,Low,Recovered,NaN,South,H2

,Patient_ID,Age,Gender,Hospital,Hospital_Type,Diagnosis,Treatment_Cost,Doctor_Experience_Years,Doctor_Availability,Cleanliness_Score,Economic_Status,Outcome,Insurance,Region,Hospital_ID
0,P10000,69.0,MALE,CarePoint,Private,Asthma,20527.617,1.0,5,3,Middle,Recovered,No,West,H3
1,P10001,32.0,MALE,CarePoint,Private,Covid,31587.963,34.0,5,2,Middle,Under Treatment,Yes,West,H3
2,P10002,NaN,female,CarePoint,Private,Covid,44728.453,25.0,7,4,Low,Under Treatment,NaN,north,H3
3,P10003,38.0,Female,CarePoint,Private,Covid,37211.526,34.0,3,3,Middle,Recovered,No,north,H3
4,P10004,41.0,female,CarePoint,Private,Asthma,13885.256,21.0,11,5,Low,Recovered,NaN,South,H3

In [4]:
print('Rows:', len(df_1))
print('Columns:', len(df_1.columns))
df_1.info()

Rows: 8000
Columns: 15
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               8000 non-null   str
 1   Age                      7360 non-null   float64
 2   Gender                   8000 non-null   str
 3   Hospital                 8000 non-null   str
 4   Hospital_Type            8000 non-null   str
 5   Diagnosis                8000 non-null   str
 6   Treatment_Cost           7360 non-null   float64
 7   Doctor_Experience_Years  7360 non-null   float64
 8   Doctor_Availability      8000 non-null   int64
 9   Cleanliness_Score        8000 non-null   int64
 10  Economic_Status          8000 non-null   str
 11  Outcome                  8000 non-null   str
 12  Insurance                5322 non-null   str
 13  Region                   8000 non-null   str
 14  Hospital_ID              8000 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 937.6 KB

In [5]:
print('Rows:', len(df_2))
print('Columns:', len(df_2.columns))
df_2.info()

Rows: 8000
Columns: 15
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               8000 non-null   str
 1   Age                      7360 non-null   float64
 2   Gender                   8000 non-null   str
 3   Hospital                 8000 non-null   str
 4   Hospital_Type            8000 non-null   str
 5   Diagnosis                8000 non-null   str
 6   Treatment_Cost           7360 non-null   float64
 7   Doctor_Experience_Years  7360 non-null   float64
 8   Doctor_Availability      8000 non-null   int64
 9   Cleanliness_Score        8000 non-null   int64
 10  Economic_Status          8000 non-null   str
 11  Outcome                  8000 non-null   str
 12  Insurance                5322 non-null   str
 13  Region                   8000 non-null   str
 14  Hospital_ID              8000 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 937.6 KB

In [6]:
print('Rows:', len(df_3))
print('Columns:', len(df_3.columns))
df_3.info()

Rows: 8000
Columns: 15
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               8000 non-null   str
 1   Age                      7360 non-null   float64
 2   Gender                   8000 non-null   str
 3   Hospital                 8000 non-null   str
 4   Hospital_Type            8000 non-null   str
 5   Diagnosis                8000 non-null   str
 6   Treatment_Cost           7360 non-null   float64
 7   Doctor_Experience_Years  7360 non-null   float64
 8   Doctor_Availability      8000 non-null   int64
 9   Cleanliness_Score        8000 non-null   int64
 10  Economic_Status          8000 non-null   str
 11  Outcome                  8000 non-null   str
 12  Insurance                5322 non-null   str
 13  Region                   8000 non-null   str
 14  Hospital_ID              8000 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 937.6 KB